### ISSUE TITLE
[Question] 请问在初始情况下如何生成zh-CN.json呢？

### ISSUE THREAD

**Issue by AngelicElegy** [lobehub/lobe-cli-toolbox#106]
### 🧐 问题描述 | Proposed Solution

i18n的相关文件，我都是写在/src/locales/default中的嘛，然后这些都是ts文件，我应该怎么初始化在/locales中生成default对应的zh-CN.json文件呢？

**Comment by AngelicElegy** [comment]
因为我看 lobe-i18n 这个命令是依赖于 /locales/zh-CN.json的，这个zh-CN.json如何自动生成呢？

**Comment by canisminor1990** [comment]
> 因为我看 lobe-i18n 这个命令是依赖于 /locales/zh-CN.json的，这个zh-CN.json如何自动生成呢？

可以参考 lobe-chat scripts 中的内容
