### ISSUE TITLE
[Question] lobe-i18n - ERROR  Can't find config

### ISSUE THREAD

**Issue by shinshin86** [lobehub/lobe-cli-toolbox#156]
### 🧐 问题描述 | Proposed Solution

I followed the instructions in the README and ran the following commands:

```sh
npm install --save-dev @lobehub/i18n-cli
npx lobe-i18n --option
npx lobe-i18n locale
```

OpenAI token is set
![lobe-i18n_openai_token](https://github.com/user-attachments/assets/b5a252ad-313d-4e1d-9c2d-49e3fe9a634a)

However, when I executed npx lobe-i18n locale, I encountered the following error:

```sh
ERROR  Can't find config
```

Am I missing any additional configuration? Based on the README, I expected it to work with these steps, but if there’s anything else required, could you please let me know?

**Comment by canisminor1990** [comment]
https://github.com/lobehub/lobe-cli-toolbox/blob/master/packages/lobe-i18n/README.md#configuration

**Comment by shinshin86** [comment]
@canisminor1990 Thank you for your response!

It seems I had overlooked the need to prepare a configuration file, but your advice helped me realize this.
Thanks to you, I was able to get everything up and running successfully and take the first step in utilizing lobe-i18n.

Thank you so much!

(This issue has been resolved, so I will close it.)
