### ISSUE TITLE
md i18n bug

### ISSUE THREAD

**Issue by arvinxx** [lobehub/lobe-cli-toolbox#51]
1.  链接错位，在英文里被识别成 link 了，且位置不正确。

![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/9bdf1819-1ec0-477e-9723-62e5313d2687)

![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/aac40e47-b2c4-4fe4-a363-f536cb22866c)

2. 翻译内容丢失
![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/00b564fc-b18f-417d-9c68-da1001dc2b44)
原文内容：
![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/2fd6c281-911c-4870-b8f7-7e3e274d8dd3)

文件：[use-on-standalone-init.md](https://github.com/lobehub/lobe-cli-toolbox/files/13433216/use-on-standalone-init.md)

3. 标题翻译处理问题

![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/bd18962f-d999-4610-9ec4-b01982f19fba)

原始内容：

![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/73b551f6-ed92-4852-9aea-d5b206938b6f)

文件：[submit-market.zh-CN.md](https://github.com/lobehub/lobe-cli-toolbox/files/13433239/submit-market.zh-CN.md)

4. 翻译问题

![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/355e0cca-0143-422c-8c54-60b2e8a113a3)

原始内容：
![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/21d6bd67-4113-42de-ae7d-7ffeb252e139)

直接翻译没问题：
![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/95e49b31-2335-4b99-afdc-f46e7a80e182)

5. markdown 标记问题

![image](https://github.com/lobehub/lobe-cli-toolbox/assets/28616219/8115e104-0f5c-49a2-a7c6-40683acb5860)

**Comment by canisminor1990** [comment]
https://github.com/lobehub/lobe-cli-toolbox/commit/e599f6091d41fb3e8367dc1b5ec069d0d79e4681
